### ISSUE TITLE
problem reading remappings from foundry.toml

### ISSUE THREAD

**Issue by devtooligan** [defi-wonderland/natspec-smells#34]
Hey guys this is great, thanks for making it! I've been meaning to try this out for a while and had the opportunity to do it today.

For some reason it couldn't get the remappings out of the foundry.toml.

```
remappings = ["openzeppelin/=lib/openzeppelin-contracts/contracts"]
```

but when i created a remappings.txt file, it worked:
```
openzeppelin/=lib/openzeppelin-contracts/contracts
```

**Comment by gas1cent** [comment]
This issue will be fixed in the next release, most likely this week.
