### ISSUE TITLE
Exit with code 1 when an issue is found

### ISSUE THREAD

**Issue by benesjan** [defi-wonderland/natspec-smells#46]
Currently the command does not fail with exit code 1 when an issue is found. This makes it impractical to use in CI.

**Comment by gas1cent** [comment]
Agree, it makes total sense. Thanks for the feedback!

**Comment by srdtrk** [comment]
Any updates on this issue? I can open a PR there is no progress.

**Comment by gas1cent** [comment]
@srdtrk I will make a PR next week

**Comment by gas1cent** [comment]
@srdtrk @benesjan please try v1.1.5

**Comment by srdtrk** [comment]
Works for me :)
