### ISSUE TITLE
Support solidity 0.8.25

### ISSUE THREAD

**Issue by beeb** [defi-wonderland/natspec-smells#50]
Would it be possible to update the version of `solc-typed-ast` so that we can use solidity 0.8.25?

I understand that `solc-typed-ast` has not yet released a new version for solidity 0.8.26 but it would be already good to support 25.

**Comment by gas1cent** [comment]
@beeb done ser, please try v1.1.2 and let us know if you need anything else.

**Comment by beeb** [comment]
Seems like the package still depends on the outdated version

https://github.com/defi-wonderland/natspec-smells/blob/a7e47bca42799863fb6b13f04996cdb9240099ff/package.json#L31

It should read 18.1.6

**Comment by gas1cent** [comment]
My bad! The change must have gotten lost in the branch-switching shenanigans. We'll fix that asap.

**Comment by gas1cent** [comment]
@beeb please check out v1.1.3, it supports Solidity 0.8.25

**Comment by beeb** [comment]
All good now! thanks
